import type { Metadata } from "next";
import { Poppins, Volkhov } from "next/font/google";
import "./_styles/global.scss"
import BsImport from "./_libs/bs-import";
import Header from "./_components/header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-poppins',
  display: 'swap',
});

const volkhov = Volkhov({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-volkhov',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${volkhov.variable}`}>
        <BsImport />
        <Header />
        {children}
      </body>
    </html>
  );
}